# Generated by Django 5.1.15 on 2026-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField()),
                (
                    "image_url",
                    models.ImageField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to="products/master/",
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("depth", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "product_masters",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("size", models.CharField(max_length=20)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
                ("sku_code", models.CharField(max_length=50, unique=True)),
                (
                    "barcode_image_url",
                    models.ImageField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to="products/barcode/",
                    ),
                ),
            ],
            options={
                "db_table": "product_variants",
            },
        ),
        migrations.CreateModel(
            name="StoreInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stock_quantity", models.IntegerField(default=0)),
                ("safety_stock", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "store_inventories",
            },
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("PAUSED", "Paused")],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "store_products",
            },
        ),
    ]
