# Generated by Django 5.1.15 on 2026-04-22 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaster",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product_master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.productmaster",
            ),
        ),
        migrations.AddField(
            model_name="storeinventory",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="storeinventory",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="product_master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_assignments",
                to="products.productmaster",
            ),
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handled_products",
                to="stores.store",
            ),
        ),
        migrations.AddConstraint(
            model_name="storeinventory",
            constraint=models.UniqueConstraint(
                fields=("store", "variant"), name="uq_store_variant_inventory"
            ),
        ),
        migrations.AddConstraint(
            model_name="storeproduct",
            constraint=models.UniqueConstraint(
                fields=("store", "product_master"), name="uq_store_products"
            ),
        ),
    ]
