# Generated by Django 5.1.15 on 2026-04-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmaster",
            name="image_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
