# Generated by Django 5.1.15 on 2026-04-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_productmaster_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmaster",
            name="depth",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productmaster",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productmaster",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
