# Generated by Django 5.1.15 on 2026-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0004_alter_productmaster_depth_alter_productmaster_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="sku_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("sku_code",),
                name="uq_alive_variant_sku",
            ),
        ),
    ]
