# Generated by Django 5.1.15 on 2026-05-12 08:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets_3d", "0003_alter_asset3d_target_type_and_more"),
        ("fixtures", "0002_initial"),
        ("products", "0005_alter_productvariant_sku_code_and_more"),
        ("stores", "0005_storemember_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetectionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "source_image_key",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("callback_token", models.CharField(max_length=128)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fixture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_detection_tasks",
                        to="fixtures.fixturemaster",
                    ),
                ),
                (
                    "fixture_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_detection_tasks",
                        to="fixtures.fixtureversion",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_product_detection_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_detection_tasks",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "product_detection_tasks",
            },
        ),
        migrations.CreateModel(
            name="ProductDetectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(49),
                        ]
                    ),
                ),
                ("thumbnail_key", models.CharField(max_length=512)),
                (
                    "relative_position_x",
                    models.DecimalField(decimal_places=6, max_digits=8),
                ),
                (
                    "relative_position_y",
                    models.DecimalField(decimal_places=6, max_digits=8),
                ),
                (
                    "relative_size_width",
                    models.DecimalField(decimal_places=6, max_digits=8),
                ),
                (
                    "relative_size_height",
                    models.DecimalField(decimal_places=6, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DETECTED", "Detected"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Rejected"),
                            ("REGISTERED", "Registered"),
                        ],
                        default="DETECTED",
                        max_length=20,
                    ),
                ),
                (
                    "asset_generation_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUESTED", "Not Requested"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="NOT_REQUESTED",
                        max_length=20,
                    ),
                ),
                ("asset_error_message", models.TextField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("bbox_xyxy", models.JSONField(blank=True, null=True)),
                (
                    "asset_3d",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detection_items",
                        to="assets_3d.asset3d",
                    ),
                ),
                (
                    "asset_generation_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detection_items",
                        to="assets_3d.assetgenerationtask",
                    ),
                ),
                (
                    "product_master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detection_items",
                        to="products.productmaster",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detection_items",
                        to="products.productvariant",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.productdetectiontask",
                    ),
                ),
            ],
            options={
                "db_table": "product_detection_items",
            },
        ),
        migrations.AddIndex(
            model_name="productdetectiontask",
            index=models.Index(
                fields=["status", "created_at"], name="idx_det_task_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="productdetectiontask",
            index=models.Index(
                fields=["store", "created_at"], name="idx_det_task_store_created"
            ),
        ),
        migrations.AddIndex(
            model_name="productdetectiontask",
            index=models.Index(
                fields=["requested_by", "created_at"], name="idx_det_task_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="productdetectiontask",
            index=models.Index(
                fields=["fixture", "created_at"], name="idx_det_task_fixture_created"
            ),
        ),
        migrations.AddIndex(
            model_name="productdetectionitem",
            index=models.Index(
                fields=["task", "status"], name="idx_detection_item_task_status"
            ),
        ),
        migrations.AddIndex(
            model_name="productdetectionitem",
            index=models.Index(
                fields=["task", "asset_generation_status"],
                name="idx_det_item_task_asset_stat",
            ),
        ),
        migrations.AddIndex(
            model_name="productdetectionitem",
            index=models.Index(
                fields=["asset_generation_task"], name="idx_detection_item_asset_task"
            ),
        ),
        migrations.AddIndex(
            model_name="productdetectionitem",
            index=models.Index(fields=["asset_3d"], name="idx_detection_item_asset_3d"),
        ),
        migrations.AddConstraint(
            model_name="productdetectionitem",
            constraint=models.UniqueConstraint(
                fields=("task", "slot"), name="uniq_detection_item_task_slot"
            ),
        ),
    ]
