# Generated by Django 5.1.15 on 2026-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset3D",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("FIXTURE", "Fixture"),
                            ("STORE", "Store"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.BigIntegerField()),
                (
                    "file_format",
                    models.CharField(
                        choices=[("GLB", "Glb"), ("GLTF", "Gltf"), ("OBJ", "Obj")],
                        max_length=10,
                    ),
                ),
                ("model_url", models.FileField(max_length=512, upload_to="assets/3d/")),
                ("file_size_bytes", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "assets_3d",
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"], name="idx_asset_target"
                    )
                ],
            },
        ),
    ]
