# Generated by Django 5.1.15 on 2026-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets_3d", "0002_asset3d_ply_and_generation_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset3d",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("PRODUCT", "Product"),
                    ("FIXTURE", "Fixture"),
                    ("STORE", "Store"),
                    ("DETECTION_ITEM", "Detection Item"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assetgenerationtask",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("PRODUCT", "Product"),
                    ("FIXTURE", "Fixture"),
                    ("STORE", "Store"),
                    ("DETECTION_ITEM", "Detection Item"),
                ],
                max_length=20,
            ),
        ),
    ]
