# Generated by Django 5.1.15 on 2026-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FixtureMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("depth", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "fixture_masters",
            },
        ),
        migrations.CreateModel(
            name="FixtureVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "fixture_versions",
            },
        ),
        migrations.CreateModel(
            name="FixtureVersionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_pos_x", models.IntegerField()),
                ("local_pos_y", models.IntegerField()),
                ("local_pos_z", models.IntegerField()),
                ("memo", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DISPLAY", "Display")],
                        default="DISPLAY",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "fixture_version_products",
            },
        ),
    ]
