# Generated by Django 5.1.15 on 2026-04-22 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fixtures", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fixturemaster",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fixtures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixtureversion",
            name="fixture_master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="fixtures.fixturemaster",
            ),
        ),
        migrations.AddField(
            model_name="fixtureversionproduct",
            name="fixture_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="placements",
                to="fixtures.fixtureversion",
            ),
        ),
        migrations.AddField(
            model_name="fixtureversionproduct",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixture_placements",
                to="products.productvariant",
            ),
        ),
    ]
