# Generated by Django 5.1.15 on 2026-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("max_admin_count", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("depth", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "stores",
            },
        ),
        migrations.CreateModel(
            name="StoreImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("FLOORPLAN", "Floorplan"),
                            ("ACTUAL_PHOTO", "Actual Photo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(max_length=512, upload_to="stores/images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "store_images",
            },
        ),
        migrations.CreateModel(
            name="StoreInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invitee_email", models.EmailField(max_length=100)),
                ("invite_token", models.CharField(max_length=255, unique=True)),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("VMD", "Vmd"),
                            ("STAFF", "Staff"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "store_invitations",
            },
        ),
        migrations.CreateModel(
            name="StoreMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("VMD", "Vmd"),
                            ("STAFF", "Staff"),
                        ],
                        default="STAFF",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "store_members",
            },
        ),
    ]
