# Generated by Django 5.1.15 on 2026-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="max_admin_count",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
