# Generated by Django 5.1.15 on 2026-04-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0003_alter_store_max_admin_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeinvitation",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("MANAGER", "Manager"),
                    ("VICE_MANAGER", "Vice Manager"),
                    ("VMD", "Vmd"),
                    ("STAFF", "Staff"),
                ],
                default="MANAGER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="storemember",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("MANAGER", "Manager"),
                    ("VICE_MANAGER", "Vice Manager"),
                    ("VMD", "Vmd"),
                    ("STAFF", "Staff"),
                ],
                default="STAFF",
                max_length=20,
            ),
        ),
    ]
