# Generated by Django 5.1.15 on 2026-04-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0004_alter_storeinvitation_target_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storemember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
