# Generated by Django 5.1.15 on 2026-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("comment", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "db_table": "layouts",
            },
        ),
        migrations.CreateModel(
            name="LayoutFixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("world_pos_x", models.IntegerField()),
                ("world_pos_y", models.IntegerField()),
                ("world_pos_z", models.IntegerField()),
                ("world_rot_y", models.SmallIntegerField()),
            ],
            options={
                "db_table": "layout_fixtures",
            },
        ),
    ]
