# Generated by Django 5.1.15 on 2026-04-22 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fixtures", "0001_initial"),
        ("layouts", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="layout",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layouts",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="layoutfixture",
            name="fixture_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="layout_placements",
                to="fixtures.fixtureversion",
            ),
        ),
        migrations.AddField(
            model_name="layoutfixture",
            name="layout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fixtures",
                to="layouts.layout",
            ),
        ),
    ]
